global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8000']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8000']
